default = "run"

[vars]
CXX      = "g++ -std=c++17"
OUT      = "../Calamit/Calamit"

RAYLIB   = "-Ilibs/raylib/include -Llibs/raylib/lib -l:libraylib.a"
LUAJIT   = "-Ilibs/luajit/include -Llibs/luajit/lib -l:libluajit.a"
SYSTEM   = "-Iheaders -lpthread -ldl -lm -lX11"


[clean]
desc = "Очистка"
run = [
    "rm -f ${OUT}",
    "rm -rf ../Calamit/lua"
    "rm -rf ../Calamit/config.lua"
]

[build]
desc = "Сборка Calamit"
deps = ["clean"]
run = [
    "mkdir -p ../Calamit",
    "${CXX} main.cpp -o ${OUT} ${RAYLIB} ${LUAJIT} ${SYSTEM}",
    "cp -r config.lua ../Calamit/",
    "cp -r lua ../Calamit/"
]

[run]
desc = "Запуск Calamit"
deps = ["build"]
run = ["cd ../Calamit && ./Calamit"]
