default = "run"

[vars]
CXX      = "g++ -std=c++17 -O2 -Wall -Wextra"
OUT      = "Calamit"
OUT_DIR  = ".."

RAYLIB   = "-Ilibs/raylib/include -Llibs/raylib/lib -l:libraylib.a"
LUAJIT   = "-Ilibs/luajit/include -Llibs/luajit/lib -l:libluajit.a"
SYSTEM   = "-Iheaders -lpthread -ldl -lm -lX11"

[clean]
desc = "Очистка"
run = [
    "rm -f ${OUT_DIR}/${OUT}/${OUT}",
    "rm -f ${OUT_DIR}/${OUT}/config.lua",
    "rm -rf ${OUT_DIR}/${OUT}/lua",
]

[build]
desc = "Сборка Calamit"
deps = ["clean"]
run = [
    "mkdir -p ${OUT_DIR}/${OUT}",
    "${CXX} main.cpp -o ${OUT_DIR}/${OUT}/${OUT} ${RAYLIB} ${LUAJIT} ${SYSTEM}",
    "cp config.lua ${OUT_DIR}/${OUT}/",
    "cp -r lua ${OUT_DIR}/${OUT}/",
]

[run]
desc = "Запуск Calamit"
deps = ["build"]
run = [ "cd ${OUT_DIR}/${OUT} && ./${OUT}" ]
